spring:
  application:
    name: findex

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  datasource:
    driver-class-name: org.h2.Driver
    # 내장: 파일 모드 + 다중 접속 허용(IntelliJ 동시 사용) + PostgreSQL 호환 모드
    url: jdbc:h2:~/findex;AUTO_SERVER=TRUE;MODE=PostgreSQL
    username: findex
    password: 1234

    hikari:
      connection-timeout: 60000
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 10000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  jpa:
    hibernate:
      ddl-auto: create-drop # 운영시 반드시 none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # 애플리케이션 시작 시 배치 작업 자동 실행 (필요 시 true)

server:
  port: 8098
  servlet:
    encoding:
      charset: UTF-8
      force: true

logging:
  level:
    root: info
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.batch: DEBUG

decorator:
  datasource:
    enabled: true                  # P6Spy 및 데이터소스 데코레이터 전체 활성화 여부 (기본값: true)
    p6spy:
      enable-logging: true         # SQL 로깅 기능 자체를 켤지 끄를지 결정
      multiline: true              # 쿼리를 여러 줄로 포맷팅하여 출력 (가독성 매우 향상됨)
      logging: slf4j               # 로그 출력 방식 (sysout, slf4j, file 등. slf4j 권장)
      log-filter:
        pattern: ".*"              # 정규식 패턴을 사용하여 특정 쿼리만 로깅하거나 제외 가능